/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWhatsappRouteImport } from './routes/_authenticated/whatsapp'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as AuthenticatedRadarRouteImport } from './routes/_authenticated/radar'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedFunilRouteImport } from './routes/_authenticated/funil'
import { Route as AuthenticatedFollowupsRouteImport } from './routes/_authenticated/followups'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as ApiWebhooksEvolutionRouteImport } from './routes/api/webhooks/evolution'
import { Route as ApiWebhooksEvolutionSplatRouteImport } from './routes/api/webhooks/evolution/$'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWhatsappRoute = AuthenticatedWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRadarRoute = AuthenticatedRadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFunilRoute = AuthenticatedFunilRouteImport.update({
  id: '/funil',
  path: '/funil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFollowupsRoute = AuthenticatedFollowupsRouteImport.update({
  id: '/followups',
  path: '/followups',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiWebhooksEvolutionRoute = ApiWebhooksEvolutionRouteImport.update({
  id: '/api/webhooks/evolution',
  path: '/api/webhooks/evolution',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksEvolutionSplatRoute =
  ApiWebhooksEvolutionSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => ApiWebhooksEvolutionRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/followups': typeof AuthenticatedFollowupsRoute
  '/funil': typeof AuthenticatedFunilRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/radar': typeof AuthenticatedRadarRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/api/webhooks/evolution': typeof ApiWebhooksEvolutionRouteWithChildren
  '/api/webhooks/evolution/$': typeof ApiWebhooksEvolutionSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/followups': typeof AuthenticatedFollowupsRoute
  '/funil': typeof AuthenticatedFunilRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/radar': typeof AuthenticatedRadarRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/api/webhooks/evolution': typeof ApiWebhooksEvolutionRouteWithChildren
  '/api/webhooks/evolution/$': typeof ApiWebhooksEvolutionSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/followups': typeof AuthenticatedFollowupsRoute
  '/_authenticated/funil': typeof AuthenticatedFunilRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/radar': typeof AuthenticatedRadarRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/_authenticated/whatsapp': typeof AuthenticatedWhatsappRoute
  '/api/webhooks/evolution': typeof ApiWebhooksEvolutionRouteWithChildren
  '/api/webhooks/evolution/$': typeof ApiWebhooksEvolutionSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/configuracoes'
    | '/dashboard'
    | '/followups'
    | '/funil'
    | '/leads'
    | '/radar'
    | '/templates'
    | '/whatsapp'
    | '/api/webhooks/evolution'
    | '/api/webhooks/evolution/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/configuracoes'
    | '/dashboard'
    | '/followups'
    | '/funil'
    | '/leads'
    | '/radar'
    | '/templates'
    | '/whatsapp'
    | '/api/webhooks/evolution'
    | '/api/webhooks/evolution/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/followups'
    | '/_authenticated/funil'
    | '/_authenticated/leads'
    | '/_authenticated/radar'
    | '/_authenticated/templates'
    | '/_authenticated/whatsapp'
    | '/api/webhooks/evolution'
    | '/api/webhooks/evolution/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiWebhooksEvolutionRoute: typeof ApiWebhooksEvolutionRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/whatsapp': {
      id: '/_authenticated/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AuthenticatedWhatsappRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/radar': {
      id: '/_authenticated/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof AuthenticatedRadarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/funil': {
      id: '/_authenticated/funil'
      path: '/funil'
      fullPath: '/funil'
      preLoaderRoute: typeof AuthenticatedFunilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/followups': {
      id: '/_authenticated/followups'
      path: '/followups'
      fullPath: '/followups'
      preLoaderRoute: typeof AuthenticatedFollowupsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/webhooks/evolution': {
      id: '/api/webhooks/evolution'
      path: '/api/webhooks/evolution'
      fullPath: '/api/webhooks/evolution'
      preLoaderRoute: typeof ApiWebhooksEvolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/evolution/$': {
      id: '/api/webhooks/evolution/$'
      path: '/$'
      fullPath: '/api/webhooks/evolution/$'
      preLoaderRoute: typeof ApiWebhooksEvolutionSplatRouteImport
      parentRoute: typeof ApiWebhooksEvolutionRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFollowupsRoute: typeof AuthenticatedFollowupsRoute
  AuthenticatedFunilRoute: typeof AuthenticatedFunilRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedRadarRoute: typeof AuthenticatedRadarRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedWhatsappRoute: typeof AuthenticatedWhatsappRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFollowupsRoute: AuthenticatedFollowupsRoute,
  AuthenticatedFunilRoute: AuthenticatedFunilRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedRadarRoute: AuthenticatedRadarRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedWhatsappRoute: AuthenticatedWhatsappRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiWebhooksEvolutionRouteChildren {
  ApiWebhooksEvolutionSplatRoute: typeof ApiWebhooksEvolutionSplatRoute
}

const ApiWebhooksEvolutionRouteChildren: ApiWebhooksEvolutionRouteChildren = {
  ApiWebhooksEvolutionSplatRoute: ApiWebhooksEvolutionSplatRoute,
}

const ApiWebhooksEvolutionRouteWithChildren =
  ApiWebhooksEvolutionRoute._addFileChildren(ApiWebhooksEvolutionRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiWebhooksEvolutionRoute: ApiWebhooksEvolutionRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
